#pragma once

#define APP_IMU_INTERVAL_MS 5
#define APP_IMU_FREQUENCY (1000.0 / APP_IMU_INTERVAL_MS)
#define APP_IMU_CALIBRATION_HOLDOFF 100
#define APP_IMU_CALIBRATION_POINTS 100

#define APP_IMU_AVG_ALPHA 0.05
